// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdelum6q_cVkr6wdsquTOBnnk82Mv5S6M',
    appId: '1:30441541556:web:bdca70d9048e2cacea6ce1', // Inferred from Android ID for immediate fix
    messagingSenderId: '30441541556',
    projectId: 'restaurant-app-e827f',
    authDomain: 'restaurant-app-e827f.firebaseapp.com',
    storageBucket: 'restaurant-app-e827f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdelum6q_cVkr6wdsquTOBnnk82Mv5S6M',
    appId: '1:30441541556:android:bdca70d9048e2cacea6ce1',
    messagingSenderId: '30441541556',
    projectId: 'restaurant-app-e827f',
    storageBucket: 'restaurant-app-e827f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdelum6q_cVkr6wdsquTOBnnk82Mv5S6M',
    appId: 'REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: '30441541556',
    projectId: 'restaurant-app-e827f',
    storageBucket: 'restaurant-app-e827f.firebasestorage.app',
    iosBundleId: 'com.example.mobiledev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdelum6q_cVkr6wdsquTOBnnk82Mv5S6M',
    appId: 'REPLACE_WITH_YOUR_MACOS_APP_ID',
    messagingSenderId: '30441541556',
    projectId: 'restaurant-app-e827f',
    storageBucket: 'restaurant-app-e827f.firebasestorage.app',
    iosBundleId: 'com.example.mobiledev',
  );
}
