import 'package:flutter/material.dart';

class AppSettingsProvider extends ChangeNotifier {
  // Theme Mode
  ThemeMode _themeMode = ThemeMode.dark;
  ThemeMode get themeMode => _themeMode;

  bool get isDarkMode => _themeMode == ThemeMode.dark;

  void toggleTheme() {
    _themeMode = _themeMode == ThemeMode.dark
        ? ThemeMode.light
        : ThemeMode.dark;
    notifyListeners();
  }

  // Language
  String _language = 'en';
  String get language => _language;

  void setLanguage(String lang) {
    _language = lang;
    notifyListeners();
  }

  // Translations
  Map<String, Map<String, String>> translations = {
    'en': {
      'ordersOfTheDay': 'Orders of the Day',
      'search': 'Search',
      'categories': 'Categories',
      'accept': 'Accept',
      'refuse': 'Refuse',
      'send': 'Send',
      'cancel': 'Cancel',
      'message': 'Message',
      'suggestTime': 'Suggest Time',
      'allOrders': 'All Orders',
      'stats': 'Statistics',
      'products': 'Products',
      'tomorrowPlanned': 'Tomorrow Planned',
      'home': 'Home',
      'orders': 'Orders',
      'upcoming': 'Upcoming',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgotPassword': 'Forgot Password?',
      'noAccount': "Don't have an account? Sign up",
      'welcomeBack': 'Welcome Back',
      'signInContinue': 'Please sign in to continue',
      'logout': 'Logout',
      'sendMessage': 'Send Message',
      'to': 'To',
      'suggestAlternativeTime': 'Suggest Alternative Time (Optional)',
      'selectTimeSlot': 'Select time slot...',
      'typeMessage': 'Type your message here...',
      'studentNotification':
          'The student will receive your message as a notification',
      'messageSent': 'Message sent to',
      'addNewProduct': 'Add New Product',
      'editProduct': 'Edit Product',
      'productName': 'Product Name',
      'price': 'Price',
      'category': 'Category',
      'image': 'Image',
      'uploadImage': 'Upload Image',
      'save': 'Save',
      'delete': 'Delete',
      'deleteConfirmation': 'Are you sure you want to delete this product?',
      'tomorrowsMenu': "Tomorrow's Menu",
      'addItem': 'Add Item',
      'editItem': 'Edit Item',
      'mealType': 'Meal Type',
      'selectMealType': 'Select meal type',
      'totalOrders': 'Total Orders',
      'revenue': 'Revenue',
      'avgWaitTime': 'Avg Wait Time',
      'activeUsers': 'Active Users',
      'revenueCustomerTrends': 'Revenue & Customer Trends',
      'comparisonWithLast': 'Comparison with last',
      'customers': 'Customers',
      'mostOrderedItems': 'Most Ordered Items',
      'showMore': 'Show More',
      'showLess': 'Show Less',
      'peakHours': 'Peak Hours',
      'ordersByHour': 'Orders by Hour',
      'orderStatus': 'Order Status',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'paid': 'Paid',
      'cancelled': 'Cancelled',
      'month': 'Month',
      'year': 'Year',
      'myOrders': 'My Orders',
      'orderHistory': 'Order History',
      'currentOrders': 'Current Orders',
      'total': 'Total',
      'checkout': 'Checkout',
      'cartEmpty': 'Your Cart is Empty',
      'addToCart': 'Add to Cart',
      'removeFromCart': 'Remove from Cart',
      'pickupTime': 'Pickup Time',
      'quantity': 'Quantity',
      'items': 'Items',
      'accepted': 'Accepted',
      'refused': 'Refused',
      'searchOrders': 'Search orders...',
      'no': 'No',
      'revenueTrends': 'Revenue & Customer Trends',
      'comparison': 'Comparison with last',
      'fromYesterday': 'from yesterday',
      'newUsers': 'new users',
      'ordersByHourMorning': 'Orders by Hour (8 AM - 2 PM)',
      'ordersByHourEvening': 'Orders by Hour (3 PM - 9 PM)',
      'menuItemUpdated': 'Menu item updated',
      'itemAddedToMenu': 'Item added to menu',
      'statistics': 'Statistics',
      'votes': 'Votes',
      'changeLanguage': 'Change Language',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'orderNumber': 'Order #',
      'acceptOrderConfirmation':
          'Are you sure you want to accept the order from',
      'orderFrom': 'Order from',
      'acceptedSuffix': 'accepted',
      'refuseOrderConfirmation':
          'Are you sure you want to refuse the order from',
      'refusedSuffix': 'refused',
      'productAdded': 'Product added successfully',
      'productUpdated': 'Product updated successfully',
      'productDeleted': 'deleted',
      'suggestedTime': 'Suggested time',
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'accessDenied': 'Access denied. Admin privileges required.',
      'required': 'Required',
      'contactIT': 'Please contact IT support to reset your password.',
      'securedBy': 'Secured by UEMF IT',
      'invalidCredentials': 'Invalid username or password',
      'respondToOrder': 'Respond to Order',
      'filterByStatus': 'Filter by Status',
      'filterBy': 'Filter by',
      'totalVotes': 'Total Votes',
      'topRequested': 'Top Requested',
      'noItemsFound': 'No items found',
      'changeImage': 'Change Image',
      'itemUpdated': 'Item updated',
      'itemDeleted': 'Item deleted',
      'all': 'All',
    },
    'fr': {
      'ordersOfTheDay': 'Commandes du jour',
      'search': 'Rechercher',
      'categories': 'Catégories',
      'accept': 'Accepter',
      'refuse': 'Refuser',
      'send': 'Envoyer',
      'cancel': 'Annuler',
      'message': 'Message',
      'suggestTime': 'Suggérer un horaire',
      'allOrders': 'Toutes les commandes',
      'stats': 'Statistiques',
      'products': 'Produits',
      'tomorrowPlanned': 'Planifié pour demain',
      'home': 'Accueil',
      'orders': 'Commandes',
      'upcoming': 'À venir',
      'login': 'Connexion',
      'email': 'Email',
      'password': 'Mot de passe',
      'forgotPassword': 'Mot de passe oublié ?',
      'noAccount': "Pas de compte ? S'inscrire",
      'welcomeBack': 'Bon retour',
      'signInContinue': 'Veuillez vous connecter pour continuer',
      'logout': 'Déconnexion',
      'sendMessage': 'Envoyer un message',
      'to': 'À',
      'suggestAlternativeTime': 'Suggérer un autre horaire (Optionnel)',
      'selectTimeSlot': 'Sélectionner un créneau...',
      'typeMessage': 'Tapez votre message ici...',
      'studentNotification':
          "L'étudiant recevra votre message sous forme de notification",
      'messageSent': 'Message envoyé à',
      'addNewProduct': 'Ajouter un produit',
      'editProduct': 'Modifier le produit',
      'productName': 'Nom du produit',
      'price': 'Prix',
      'category': 'Catégorie',
      'image': 'Image',
      'uploadImage': 'Télécharger une image',
      'save': 'Enregistrer',
      'delete': 'Supprimer',
      'deleteConfirmation': 'Êtes-vous sûr de vouloir supprimer ce produit ?',
      'tomorrowsMenu': 'Menu de demain',
      'addItem': 'Ajouter un article',
      'editItem': "Modifier l'article",
      'mealType': 'Type de repas',
      'selectMealType': 'Sélectionner le type de repas',
      'totalOrders': 'Total des commandes',
      'revenue': 'Revenus',
      'avgWaitTime': 'Temps d\'attente moyen',
      'activeUsers': 'Utilisateurs actifs',
      'revenueCustomerTrends': 'Tendances revenus & clients',
      'comparisonWithLast': 'Comparaison avec le dernier',
      'customers': 'Clients',
      'mostOrderedItems': 'Articles les plus commandés',
      'showMore': 'Voir plus',
      'showLess': 'Voir moins',
      'peakHours': 'Heures de pointe',
      'ordersByHour': 'Commandes par heure',
      'orderStatus': 'Statut des commandes',
      'pending': 'En attente',
      'confirmed': 'Confirmé',
      'paid': 'Payé',
      'cancelled': 'Annulé',
      'month': 'Mois',
      'year': 'Année',
      'myOrders': 'Mes commandes',
      'orderHistory': 'Historique des commandes',
      'currentOrders': 'Commandes en cours',
      'total': 'Total',
      'checkout': 'Payer',
      'cartEmpty': 'Votre panier est vide',
      'addToCart': 'Ajouter au panier',
      'removeFromCart': 'Retirer du panier',
      'pickupTime': 'Heure de retrait',
      'quantity': 'Quantité',
      'items': 'Articles',
      'accepted': 'Accepté',
      'refused': 'Refusé',
      'searchOrders': 'Rechercher des commandes...',
      'no': 'Aucun',
      'revenueTrends': 'Tendances revenus & clients',
      'comparison': 'Comparaison avec le dernier',
      'fromYesterday': "d'hier",
      'newUsers': 'nouveaux utilisateurs',
      'ordersByHourMorning': 'Commandes par heure (8h - 14h)',
      'ordersByHourEvening': 'Commandes par heure (15h - 21h)',
      'menuItemUpdated': 'Élément du menu mis à jour',
      'itemAddedToMenu': 'Article ajouté au menu',
      'statistics': 'Statistiques',
      'votes': 'Votes',
      'changeLanguage': 'Changer de langue',
      'lightMode': 'Mode clair',
      'darkMode': 'Mode sombre',
      'orderNumber': 'Commande #',
      'acceptOrderConfirmation':
          'Êtes-vous sûr de vouloir accepter la commande de',
      'orderFrom': 'Commande de',
      'acceptedSuffix': 'acceptée',
      'refuseOrderConfirmation':
          'Êtes-vous sûr de vouloir refuser la commande de',
      'refusedSuffix': 'refusée',
      'productAdded': 'Produit ajouté avec succès',
      'productUpdated': 'Produit mis à jour avec succès',
      'productDeleted': 'supprimé',
      'suggestedTime': 'Heure suggérée',
      'breakfast': 'Petit-déjeuner',
      'lunch': 'Déjeuner',
      'dinner': 'Dîner',
      'accessDenied': 'Accès refusé. Privilèges administrateur requis.',
      'required': 'Requis',
      'contactIT':
          'Veuillez contacter le support informatique pour réinitialiser votre mot de passe.',
      'securedBy': 'Sécurisé par UEMF IT',
      'invalidCredentials': 'Nom d\'utilisateur ou mot de passe invalide',
      'respondToOrder': 'Répondre à la commande',
      'filterByStatus': 'Filtrer par statut',
      'filterBy': 'Filtrer par',
      'totalVotes': 'Total des votes',
      'topRequested': 'Le plus demandé',
      'noItemsFound': 'Aucun article trouvé',
      'changeImage': 'Changer l\'image',
      'itemUpdated': 'Article mis à jour',
      'itemDeleted': 'Article supprimé',
      'all': 'Tout',
    },
    'ar': {
      'ordersOfTheDay': 'طلبات اليوم',
      'search': 'بحث',
      'categories': 'الفئات',
      'accept': 'قبول',
      'refuse': 'رفض',
      'send': 'إرسال',
      'cancel': 'إلغاء',
      'message': 'رسالة',
      'suggestTime': 'اقتراح وقت',
      'allOrders': 'كل الطلبات',
      'stats': 'إحصائيات',
      'products': 'المنتجات',
      'tomorrowPlanned': 'مخطط لغدا',
      'home': 'الرئيسية',
      'orders': 'الطلبات',
      'upcoming': 'القادمة',
      'login': 'تسجيل الدخول',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'noAccount': "ليس لديك حساب؟ سجل الآن",
      'welcomeBack': 'مرحباً بعودتك',
      'signInContinue': 'يرجى تسجيل الدخول للمتابعة',
      'logout': 'تسجيل الخروج',
      'sendMessage': 'إرسال رسالة',
      'to': 'إلى',
      'suggestAlternativeTime': 'اقتراح وقت بديل (اختياري)',
      'selectTimeSlot': 'اختر وقتاً...',
      'typeMessage': 'اكتب رسالتك هنا...',
      'studentNotification': 'سيتلقى الطالب رسالتك كإشعار',
      'messageSent': 'تم إرسال الرسالة إلى',
      'addNewProduct': 'إضافة منتج جديد',
      'editProduct': 'تعديل المنتج',
      'productName': 'اسم المنتج',
      'price': 'السعر',
      'category': 'الفئة',
      'image': 'صورة',
      'uploadImage': 'رفع صورة',
      'save': 'حفظ',
      'delete': 'حذف',
      'deleteConfirmation': 'هل أنت متأكد أنك تريد حذف هذا المنتج؟',
      'tomorrowsMenu': 'قائمة الغد',
      'addItem': 'إضافة عنصر',
      'editItem': 'تعديل العنصر',
      'mealType': 'نوع الوجبة',
      'selectMealType': 'اختر نوع الوجبة',
      'totalOrders': 'إجمالي الطلبات',
      'revenue': 'الإيرادات',
      'avgWaitTime': 'متوسط وقت الانتظار',
      'activeUsers': 'المستخدمين النشطين',
      'revenueCustomerTrends': 'اتجاهات الإيرادات والعملاء',
      'comparisonWithLast': 'مقارنة مع آخر',
      'customers': 'العملاء',
      'mostOrderedItems': 'الأكثر طلباً',
      'showMore': 'عرض المزيد',
      'showLess': 'عرض أقل',
      'peakHours': 'ساعات الذروة',
      'ordersByHour': 'الطلبات بالساعة',
      'orderStatus': 'حالة الطلب',
      'pending': 'قيد الانتظار',
      'confirmed': 'مؤكد',
      'paid': 'مدفوع',
      'cancelled': 'ملغى',
      'month': 'شهر',
      'year': 'سنة',
      'myOrders': 'طلباتي',
      'orderHistory': 'سجل الطلبات',
      'currentOrders': 'الطلبات الحالية',
      'total': 'المجموع',
      'checkout': 'دفع',
      'cartEmpty': 'عربة التسوق فارغة',
      'addToCart': 'أضف إلى السلة',
      'removeFromCart': 'إزالة من السلة',
      'pickupTime': 'وقت الاستلام',
      'quantity': 'الكمية',
      'items': 'العناصر',
      'accepted': 'مقبول',
      'refused': 'مرفوض',
      'searchOrders': 'بحث عن الطلبات...',
      'no': 'لا',
      'revenueTrends': 'اتجاهات الإيرادات والعملاء',
      'comparison': 'مقارنة مع آخر',
      'fromYesterday': 'من الأمس',
      'newUsers': 'مستخدمين جدد',
      'ordersByHourMorning': 'الطلبات بالساعة (8 صباحاً - 2 مساءً)',
      'ordersByHourEvening': 'الطلبات بالساعة (3 مساءً - 9 مساءً)',
      'menuItemUpdated': 'تم تحديث عنصر القائمة',
      'itemAddedToMenu': 'تم إضافة العنصر إلى القائمة',
      'statistics': 'إحصائيات',
      'votes': 'أصوات',
      'changeLanguage': 'تغيير اللغة',
      'lightMode': 'الوضع الفاتح',
      'darkMode': 'الوضع الداكن',
      'orderNumber': 'طلب #',
      'acceptOrderConfirmation': 'هل أنت متأكد أنك تريد قبول طلب',
      'orderFrom': 'طلب من',
      'acceptedSuffix': 'مقبول',
      'refuseOrderConfirmation': 'هل أنت متأكد أنك تريد رفض طلب',
      'refusedSuffix': 'مرفوض',
      'productAdded': 'تم إضافة المنتج بنجاح',
      'productUpdated': 'تم تحديث المنتج بنجاح',
      'productDeleted': 'محذوف',
      'suggestedTime': 'وقت مقترح',
      'breakfast': 'فطور',
      'lunch': 'غداء',
      'dinner': 'عشاء',
      'accessDenied': 'تم رفض الوصول. مطلوب امتيازات المسؤول.',
      'required': 'مطلوب',
      'contactIT': 'يرجى الاتصال بالدعم الفني لإعادة تعيين كلمة المرور.',
      'securedBy': 'مؤمن بواسطة UEMF IT',
      'invalidCredentials': 'اسم المستخدم أو كلمة المرور غير صحيحة',
      'respondToOrder': 'الرد على الطلب',
      'filterByStatus': 'تصفية حسب الحالة',
      'filterBy': 'تصفية حسب',
      'totalVotes': 'إجمالي الأصوات',
      'topRequested': 'الأكثر طلباً',
      'noItemsFound': 'لم يتم العثور على عناصر',
      'changeImage': 'تغيير الصورة',
      'itemUpdated': 'تم تحديث العنصر',
      'itemDeleted': 'تم حذف العنصر',
      'all': 'الكل',
    },
  };

  String t(String key) {
    return translations[_language]?[key] ?? key;
  }

  // Categories with translations
  List<Map<String, dynamic>> get categories => [
    {
      'id': 'all',
      'name': {'en': 'All', 'fr': 'Tout', 'ar': 'الكل'},
      'icon': Icons.grid_view_rounded,
    },
    {
      'id': 'hot-drinks',
      'name': {
        'en': 'Hot Drinks',
        'fr': 'Boissons chaudes',
        'ar': 'مشروبات ساخنة',
      },
      'icon': Icons.coffee_rounded,
    },
    {
      'id': 'cold-drinks',
      'name': {
        'en': 'Cold Drinks',
        'fr': 'Boissons froides',
        'ar': 'مشروبات باردة',
      },
      'icon': Icons.local_drink_rounded,
    },
    {
      'id': 'cakes-desserts',
      'name': {
        'en': 'Cakes & Desserts',
        'fr': 'Gâteaux & desserts',
        'ar': 'كعك وحلويات',
      },
      'icon': Icons.cake_rounded,
    },
    {
      'id': 'breakfast',
      'name': {'en': 'Breakfast', 'fr': 'Petit déjeuner', 'ar': 'فطور'},
      'icon': Icons.bakery_dining_rounded,
    },
    {
      'id': 'pizza-pasta',
      'name': {
        'en': 'Pizza & Pasta',
        'fr': 'Pizza & pâtes',
        'ar': 'بيتزا ومعكرونة',
      },
      'icon': Icons.local_pizza_rounded,
    },
    {
      'id': 'dishes',
      'name': {'en': 'Main Dishes', 'fr': 'Plats', 'ar': 'أطباق رئيسية'},
      'icon': Icons.dinner_dining_rounded,
    },
    {
      'id': 'sandwiches',
      'name': {'en': 'Sandwiches', 'fr': 'Sandwiches', 'ar': 'ساندويتشات'},
      'icon': Icons.lunch_dining_rounded,
    },
    {
      'id': 'salads',
      'name': {'en': 'Salads', 'fr': 'Salades', 'ar': 'سلطات'},
      'icon': Icons.eco_rounded,
    },
    {
      'id': 'dairy',
      'name': {'en': 'Dairy', 'fr': 'Laitage', 'ar': 'ألبان'},
      'icon': Icons.egg_rounded,
    },
    {
      'id': 'snacks',
      'name': {'en': 'Snacks', 'fr': 'Snacks', 'ar': 'وجبات خفيفة'},
      'icon': Icons.fastfood_rounded,
    },
  ];

  String getCategoryName(String categoryId) {
    final category = categories.firstWhere(
      (cat) => cat['id'] == categoryId,
      orElse: () => {
        'name': {'en': categoryId, 'fr': categoryId, 'ar': categoryId},
      },
    );
    return category['name'][_language] ?? categoryId;
  }
}
